version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run tests
          command: yarn build

workflows:
  heroku_deploy:
    jobs:
      - build  
