version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/tmp
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run tests
          command: yarn build
      - store_artifacts:
          path: ~/tmp/build
          destination: build
  deploy-staging:
    docker:
      - image: circleci/node:4.8.2 
    steps:
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:             
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: bucket
          to: 'S3://dummypuneetapp/x'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 'S3://dummypuneetapp'     
  request-approval:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "deploying to prod"
  deploy-stuff:
    docker:
      - image: circleci/node:4.8.2   
    steps:
      - run: echo "Deploy stuff here"

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
      - request-approval
      - hold:
          type: approval
          requires:
            - build
            - request-approval              
      - deploy-stuff:
          requires:
            - hold 
