version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    steps:
      - run:
        name: build artifact
        command: yarn build
  dependencies:
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
            
workflows:
  node-build:
    jobs:
      - build
        requires:
            - dependencies
