version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/webapp
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn build

workflows:
  heroku_deploy:
    jobs:
      - build 
