version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/tmp
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run tests
          command: yarn build
      - store_artifacts:
          path: ~/tmp/build
          destination: build        
  request-approval:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "deploying to prod"
  deploy-stuff:
    docker:
      - image: circleci/node:4.8.2   
    steps:
      - run: echo "Deploy stuff here"

workflows:
  heroku_deploy:
    jobs:
      - build
      - request-approval
      - hold:
          type: approval
          requires:
            - build
            - request-approval
      - deploy-stuff:
          requires:
            - hold 
